create sequence hibernate_sequence start with 1 increment by 1;
create table education (id bigint not null, end date, school varchar(255), start date, title varchar(255), primary key (id));
create table experence (id bigint not null, compagny_name varchar(255), details varchar(2000), end date, start date, title varchar(255), primary key (id));
create table RESUME (id bigint not null, primary key (id));
create table RESUME_educations (RESUME_id bigint not null, educations_id bigint not null);
create table RESUME_experences (RESUME_id bigint not null, experences_id bigint not null);
create table template (id bigint not null, primary key (id));
alter table RESUME_educations add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);
alter table RESUME_experences add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);
alter table RESUME_educations add constraint FK72hjtbjeh18tld36hp9kwol5h foreign key (educations_id) references education;
alter table RESUME_educations add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 foreign key (RESUME_id) references RESUME;
alter table RESUME_experences add constraint FK596vjopypx218e6l32opgf0or foreign key (experences_id) references experence;
alter table RESUME_experences add constraint FKbeebarq19ky2hxgrq8ddbw27u foreign key (RESUME_id) references RESUME;
create sequence hibernate_sequence start with 1 increment by 1;

    create table education (
       id bigint not null,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint not null,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint not null,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint not null,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       drop constraint if exists UK_93vmecn9nnf404xklm1947thi;

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       drop constraint if exists UK_pkq5w5w110ofxew8yrkqf4nm5;

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table RESUME (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table RESUME_educations (
       RESUME_id bigint not null,
        educations_id bigint not null
    );

    create table RESUME_experences (
       RESUME_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table RESUME_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table RESUME_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table RESUME_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table RESUME_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (RESUME_id) 
       references RESUME;

    alter table RESUME_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table RESUME_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (RESUME_id) 
       references RESUME;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table resume (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table resume_educations (
       resume_id bigint not null,
        educations_id bigint not null
    );

    create table resume_experences (
       resume_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table resume_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table resume_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table resume_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table resume_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (resume_id) 
       references resume;

    alter table resume_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table resume_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (resume_id) 
       references resume;

    create table education (
       id bigint generated by default as identity,
        end date,
        school varchar(255),
        start date,
        title varchar(255),
        primary key (id)
    );

    create table experence (
       id bigint generated by default as identity,
        compagny_name varchar(255),
        details varchar(2000),
        end date,
        start date,
        title varchar(255),
        primary key (id)
    );

    create table resume (
       id bigint generated by default as identity,
        primary key (id)
    );

    create table resume_educations (
       resume_id bigint not null,
        educations_id bigint not null
    );

    create table resume_experences (
       resume_id bigint not null,
        experences_id bigint not null
    );

    create table template (
       id bigint generated by default as identity,
        primary key (id)
    );

    alter table resume_educations 
       add constraint UK_93vmecn9nnf404xklm1947thi unique (educations_id);

    alter table resume_experences 
       add constraint UK_pkq5w5w110ofxew8yrkqf4nm5 unique (experences_id);

    alter table resume_educations 
       add constraint FK72hjtbjeh18tld36hp9kwol5h 
       foreign key (educations_id) 
       references education;

    alter table resume_educations 
       add constraint FK4mnl6m5vyd3yvxmc3lbnngxj6 
       foreign key (resume_id) 
       references resume;

    alter table resume_experences 
       add constraint FK596vjopypx218e6l32opgf0or 
       foreign key (experences_id) 
       references experence;

    alter table resume_experences 
       add constraint FKbeebarq19ky2hxgrq8ddbw27u 
       foreign key (resume_id) 
       references resume;
